### ISSUE TITLE
Update Account

### ISSUE THREAD

**Issue by jroq8295** [jlattimer/CRMSoapAuthJava#6]
Thanks for Java Code.

I'm able to authenticate Dynamics and I"m able to retrieve incidents and account details . 

I'm having problem while updating incident. I'm keep getting invalid SOAP . Can you please provide me sample SOAP for Update Account / Incident?

Thanks

**Comment by jlattimer** [comment]
You might look here for an example: http://mileyja.blogspot.com/2011/04/how-to-use-update-requests-in-net-and.html

**Comment by jroq8295** [comment]
Its working now.. 

Thanks lot for your help
